export const constResponses = {
    'a book or books (used for reading)': {
        'high':[
            "build a children's house",
            "ruler",
            "to eat",
            "brick",
            "cat bed",
            "absorb spilled liquid",
            "to send secret message",
            "to make music, can be used as a drum",
            "table tennis pool",
            "help with balance when doing yoga",
            "Make a book into a clock by attaching clock hands to the cover",
            "handkerchief",
            "sex toy",
            "Make a purse out of an old book",
            "used in place of a cutting board when slicing vegetables or meat",
            "juggling",
        ],
        'low':[
            "coaster",
            "fuel",
            "decoration",
            "to throw",
            "paperweight",
            "to write/draw in it",
            "space filling",
            "bookend",
            "to fill up the case",
            "to learn from",
            "to play with",
            "printing press",
            "use to elevate something",
            "to smash bugs",
            "to make a collage or scrapbook",
            "to resell",
        ],
        'gpt':[
            "Use as a place holder in a bookshelf to reserve space for other books.",
            "A flower press for DIY botanical art.",
            "Used as an elevated platform for laptop to prevent overheating.",
            "Can be hollowed out to create a hidden storage box.",
            "A weight for press down pie crust or dough when baking.",
            "Tear the pages out to use as wrapping paper.",
            "Use as a step stool to reach high places.",
            "The spine can serve as a bookmark when removed.",
            "Coasters for glasses or mugs if the books are thick and sturdy.",
            "A door stopper to hold doors open.",
            "Flatten crumpled clothes if an iron is not available.",
            "Scratched and battered books can make great Halloween decorations.",
            "A prop for movie theatre or drama skits.",
            "Can be disassembled for crafty DIY projects.",
            "Unwanted pages can be recycled as cat litter.",
            "Flip through pages to create a vintage feeling of air movement.",
        ]
    },
    'a fork or forks (used for eating)':{
        'high':[
            "If you put a rubber band around the tines of a fork it becomes a mini-trampoline for ants or other small insects",
            "Keep your drink cold by freezing a few forks and adding them to your glass",
            "play musical instruments such as the violin",
            "If you bend it by heating it you can make a bracelet out of it",
            "a toothbrush",
            "as a miror",
            "instead of a paralyzed hand",
            "sex toy",
            "CD rack",
            "tennis racket",
            "Hold a fork by the tines and use the handle to hammer in nails",
            "Curl your lashes with a cleanfork tine for",
            "to paint with a fork",
            "Use a fork to play the piano",
            "Hang forks on a string to make wind chimes or mobile art",
            "herring for the tent",
        ],
        'low':[
            "back scratcher",
            "to pick up small items like coins or beads",
            "to comb your hair",
            "as a rake",
            "thumbtack substitute",
            "scrape dirt off your shoes",
            "Use a fork to open up tightly sealed jars",
            "utensil to cook food",
            "stir a drink",
            "as a bookmark",
            'Twirling pasta around a fork before eating it',
            "pull something out from under the sofa",
            "as iron rod",
            "to make scratches in a window",
            "to cook food",
            "remove lint from clothing",
        ],
        'gpt':[
            "Use as a letter opener.",
            "A makeshift hair pin for a quick hairstyle.",
            "To hold small notes or business cards for display.",
            "As a plant labeler in a herb garden.",
            "Emergency screwdriver.",
            "A mini rake for a miniaturized, tabletop Zen garden.",
            "To draw in wet sand or create patterns in clay.",
            "A DIY fishing hook.",
            "A mini easel to hold tiny canvas for dollhouse.",
            "Jewelry hanger for lightweight, delicate pieces.",
            "To practice hand-eye coordination for toddlers.",
            "For a handcrafted wind chime.",
            "A tool to tease out knots in strings, yarns, or ropes.",
            "To anchor balloons by tying them to the fork's handle.",
            "Emergency shoehorn.",
            "As pest deterrent when stuck in the ground in a garden.",
        ]
    },
    'a tin can or tin cans (used to store perishables)':{
        'high':[
            "Using the tab of a can to make a dress/shirt",
            "Printing press",
            "use as a hat",
            "electrical connection",
            "crush it and use in ice hockey",
            "as reflector on bicycle",
            "as binoculars (with lens in them)",
            "as a pool for ants",
            "as pinhole camera",
            "as beer opener",
            "as ice cream mold",
            "use the aluminum to make trays",
            "Put four cans on their sides, board on them and skateboard",
            "take off the label and make an earring out of it",
            "cut in half and used as salt and pepper shakers",
            "a phone case",
        ],
        'low':[
            "paperweight",
            "To store items",
            "water collection",
            "as a vase for flowers",
            "to open",
            "candle holder",
            "give it to a vagrant who collects cans",
            "flattening and making objects out of them",
            "as a coin bank",
            "as ashtray",
            "as a plant pot",
            "as a washbasin",
            "as a paintbrush holder",
            "as a cooler",
            "as a waste bin",
            "As a form of art",
        ],
        'gpt':[
            "Use a tin can as a homemade megaphone.",
            "Create a wind chime out of tin cans.",
            "Build a DIY tin can robot.",
            "Use a tin can as a small dumbbell for workouts.",
            "Serve as a mold for homemade soaps.",
            "Use like a hammer in emergency situations.",
            "Make a pet food scoop out of a tin can.",
            "Develop a tin can drum set for kids.",
            "Create a homemade bank for saving coins.",
            "Use as a stencil for round shapes in art projects.",
            "Use a tin can to cut out biscuit or cookie dough.",
            "Turn into hanging lanterns for outdoor lighting.",
            "Use large tin cans as an impromptu BBQ.",
            "A tin can could function as a small trash bin for your desk.",
            "Use a tin can to catch rainwater for plants.",
            "Mount several cans on a wall to create a unique bookshelf.",
        ]
    },
}
