export const constResponses = {
    'book': {
        'high':[
            "build a children's house",
            "ruler",
            "to eat",
            "brick",
            "cat bed",
            "absorb spilled liquid",
            "to send secret message",
            "to make music, can be used as a drum",
            "table tennis pool",
            "help with balance when doing yoga",
            "Make a book into a clock by attaching clock hands to the cover",
            "handkerchief",
            "sex toy",
            "Make a purse out of an old book",
            "used in place of a cutting board when slicing vegetables or meat",
            "juggling",
        ],
        'low':[
            "coaster",
            "fuel",
            "decoration",
            "to throw",
            "paperweight",
            "to write/draw in it",
            "space filling",
            "bookend",
            "to fill up the case",
            "to learn from",
            "to play with",
            "printing press",
            "use to elevate something",
            "to smash bugs",
            "to make a collage or scrapbook",
            "to resell",
            "as doorstop",
            "to donate",
            "as files",
            "as scripture",
            "as notebook",
            "to make paper airplanes",
            "make art such as by decoupaging it onto a canvas",
            "to be buried",
        ],
    },
    'fork':{
        'high':[
            "If you put a rubber band around the tines of a fork it becomes a mini-trampoline for ants or other small insects",
            "Keep your drink cold by freezing a few forks and adding them to your glass",
            "play musical instruments such as the violin",
            "If you bend it by heating it you can make a bracelet out of it",
            "a toothbrush",
            "as a miror",
            "instead of a paralyzed hand",
            "sex toy",
            "CD rack",
            "tennis racket",
            "Hold a fork by the tines and use the handle to hammer in nails",
            "Curl your lashes with a cleanfork tine for",
            "to paint with a fork",
            "Use a fork to play the piano",
            "Hang forks on a string to make wind chimes or mobile art",
            "herring for the tent",
        ],
        'low':[
            "back scratcher",
            "to pick up small items like coins or beads",
            "to comb your hair",
            "as a rake",
            "thumbtack substitute",
            "scrape dirt off your shoes",
            "Use a fork to open up tightly sealed jars",
            "utensil to cook food",
            "stir a drink",
            "as a bookmark",
            'Twirling pasta around a fork before eating it',
            "pull something out from under the sofa",
            "as iron rod",
            "to make scratches in a window",
            "to cook food",
            "remove lint from clothing",
            "to spear food",
            "use a fork to test the doneness of meat",
            "Making patterns in soft foods like mashed potatoes",
        ]
    },
    'tin can':{
        'high':[
            "Using the tab of a can to make a dress/shirt",
            "Printing press",
            "use as a hat",
            "electrical connection",
            "crush it and use in ice hockey",
            "as reflector on bicycle",
            "as binoculars (with lens in them)",
            "as a pool for ants",
            "as pinhole camera",
            "as beer opener",
            "as ice cream mold",
            "use the aluminum to make trays",
            "Put four cans on their sides, board on them and skateboard",
            "take off the label and make",
            "take off the label and make an earring out of it",
            "cut in half and used as salt and pepper shakers",
            "a phone case",
            "as shower head",
            "Use as a mirror",
            "You can play a drinking game with the tabs",
            "as a solar oven",
            "as a handbag",
            "as a faraday cage",
        ],
        'low':[
            "paperweight",
            "To store items",
            "water collection",
            "as a vase for flowers",
            "to open",
            "candle holder",
            "give it to a vagrant who collects cans",
            "flattening and making objects out of them",
            "as a coin bank",
            "as ashtray",
            "as a plant pot",
            "as a washbasin",
            "as a paintbrush holder",
            "as a cooler",
            "as a waste bin",
            "As a form of art",
            "as a soup bowl",
            "bird feeder",
            "As a planter",
            "as a doorstop",
            "as a cup",
            "as a pan with lid",
            "decorate it and use it as a gift",
        ]
    },
}