export const constResponses = {
    'a book or books (used for reading)': {
        'high':[
            "build a children's house",
            "ruler",
            "to eat",
            "brick",
            "cat bed",
            "absorb spilled liquid",
            "to send secret message",
            "to make music, can be used as a drum",
            "table tennis pool",
            "help with balance when doing yoga",
            "Make a book into a clock by attaching clock hands to the cover",
            "handkerchief",
            "Make a purse out of an old book",
            "used in place of a cutting board when slicing vegetables or meat",
            "juggling",
        ],
        'low':[
            "coaster",
            "fuel",
            "decoration",
            "to throw",
            "paperweight",
            "to write/draw in it",
            "space filling",
            "bookend",
            "to fill up the case",
            "to learn from",
            "to play with",
            "printing press",
            "use to elevate something",
            "to smash bugs",
            "to make a collage or scrapbook",
        ],
    
        'gpt': [
            "Press dried flowers with weighted stacks for botanical art",
            "Fold pages into a secret compartment to hide small valuables",
            "Use as a makeshift laptop stand to improve airflow",
            "Create a doorstop by wedging the spine under the door",
            "Stack into a mini step to reach high shelves",
            "Tape two together as impromptu dumbbells for light workouts",
            "Carve a niche in pages to make a covert gift box",
            "Arrange as a camera tripod riser for stable height adjustment",
            "Use as a windbreak to shield a candle outdoors",
            "Slide under a wobbly table leg as a stable shim",
            "Construct a domino-style chain reaction sculpture",
            "Repurpose covers as rigid clipboard substitutes",
            "Build a laptop privacy wall in open spaces",
            "Use as a portable kneeling pad for gardening",
            "Fashion a makeshift photo reflector with white pages",
            "Create a weighted fabric press for smoothing seams",
        ],
    },
    'a fork or forks (used for eating)':{
        'high':[
            "If you put a rubber band around the tines of a fork it becomes a mini-trampoline for ants or other small insects",
            "Keep your drink cold by freezing a few forks and adding them to your glass",
            "play musical instruments such as the violin",
            "If you bend it by heating it you can make a bracelet out of it",
            "a toothbrush",
            "as a mirror",
            "instead of a paralyzed hand",
            "CD rack",
            "tennis racket",
            "Hold a fork by the tines and use the handle to hammer in nails",
            "Curl your lashes with a clean fork's tines",
            "to paint with a fork",
            "Use a fork to play the piano",
            "Hang forks on a string to make wind chimes or mobile art",
            "herring for the tent",
        ],
        'low':[
            "back scratcher",
            "to pick up small items like coins or beads",
            "to comb your hair",
            "as a rake",
            "thumbtack substitute",
            "scrape dirt off your shoes",
            "Use a fork to open up tightly sealed jars",
            "utensil to cook food",
            "stir a drink",
            "as a bookmark",
            'Twirling pasta around a fork before eating it',
            "pull something out from under the sofa",
            "as iron rod",
            "to make scratches in a window",
            "to cook food",
        ],
        'gpt': [
            "Use two forks as improvised hair curlers by wrapping damp strands around the tines",
            "Turn a fork into a plant label by etching the herb name on the handle and sticking it in soil",
            "Tape a fork to a pole as a gutter-cleaning hook for leaves",
            "Make a catapult by anchoring the handle and flicking rubber bands off the tines",
            "Use a fork as a comb to score straight lines in wet clay or putty",
            "Create a makeshift picture hanger by bending the handle into a wall hook",
            "Press fork tines into soft butter to emboss decorative patterns on pastry tops",
            "Use a fork as a keyring untangler by prying rings apart with the tines",
            "Repurpose a fork as a mini weeding tool to pry dandelions from tight spaces",
            "Glue a magnet to a fork and use it as a fridge pen holder",
            "Scrape ice off a windshield corner with the edge of a fork handle",
            "Fashion a wind chime by suspending multiple forks with fishing line",
            "Use a fork as a stencil to paint repeating striped textures",
            "Make a page stand by wedging the fork into a book spine to hold it open",
            "Hang earrings by threading them through the tines of a wall-mounted fork",
        ],
    },
    'a tin can or tin cans (used to store perishables)':{
        'high':[
            "Using the tab of a can to make a dress/shirt",
            "Printing press",
            "use as a hat",
            "electrical connection",
            "crush it and use in ice hockey",
            "as reflector on bicycle",
            "as binoculars (with lens in them)",
            "as a pool for ants",
            "as pinhole camera",
            "as beer opener",
            "as ice cream mold",
            "use the aluminum to make trays",
            "Put four cans on their sides, board on them and skateboard",
            "take off the label and make an earring out of it",
            "cut in half and used as salt and pepper shakers",
        ],
        'low':[
            "paperweight",
            "To store items",
            "water collection",
            "as a vase for flowers",
            "to open",
            "candle holder",
            "give it to someone who collects cans",
            "flattening and making objects out of them",
            "as a coin bank",
            "as ashtray",
            "as a plant pot",
            "as a washbasin",
            "as a paintbrush holder",
            "as a cooler",
            "as a waste bin",
        ],
        'gpt': [
            "Stack and fill with sand to build a modular free-weight set",
            "Turn into a wind-powered garden chime by suspending with strings",
            "Use as a seedling starter pot with drainage holes",
            "Make a compact camping stove with vent slots and pot stand",
            "Create a desktop pen-and-tool caddy with dividers from cardboard",
            "Craft a percussive drum for rhythm practice with a balloon skin",
            "Assemble a solar still condenser by cooling collected vapor",
            "Build a mini Faraday cage for small electronics storage",
            "Fashion a bird feeder with side ports and a perch rod",
            "Use as a paintbrush washing station with wire grid inside",
            "Construct a cord organizer by coiling cables inside and labeling",
            "Make a rolling cookie cutter for patterned dough embossing",
            "Create a gravity-fed string dispenser with a lid grommet",
            "Turn into a portable speaker amplifier for a phone by slotting it",
            "Use as a survival fish trap by inverting a mesh cone at the opening",
        ]
    },
}
